### ISSUE TITLE
Server selection timeout: No available servers.

### ISSUE THREAD

**Issue by sero01000** [dracarys18/grpmr-rs#1]
when i running program i got this error:
` ERROR teloxide::error_handlers > Error: Server selection timeout: No available servers. Topology: {
 Type: ReplicaSetNoPrimary, Servers: [ { Address: cluster0-shard-00-01.q8ppe.mongodb.net:27017, Type
: Unknown, Error: timed out }, { Address: cluster0-shard-00-00.q8ppe.mongodb.net:27017, Type: Unknow
n, Error: timed out }, { Address: cluster0-shard-00-02.q8ppe.mongodb.net:27017, Type: Unknown, Error
: timed out }, ] }`

**Comment by dracarys18** [comment]
Updated the mongo driver to 2.1 as the 2.0.x wasn't supporting Mondo DB 3.4 . That must fix the issue please check on your end.
[Commit link for reference](
https://github.com/dracarys18/grpmr-rs/commit/cca37f4aedb25b6308ca9bbc3f87bbd73eb89abf )

**Comment by dracarys18** [comment]
Closing the issue as the I tested it myself and runs fine.
